/*
- Table: DEVELOPER_INFOS
- Goal: 테이블에서 Python 스킬을 가진 개발자의 정보를 조회
- 핵심 컬럼: ID, EMAIL,FIRST_NAME, LAST_NAME ,SKILL_1,2,3
*/
SELECT ID, EMAIL,FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE SKILL_1 ='Python' OR SKILL_2 ='Python' OR SKILL_3 ='Python'
ORDER BY ID ASC